apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-dbnmdsnz
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-dbnmdsnz:e92e226db715e6eedbcd881a31404bf2b3899c7e@sha256:d5ef91733d4043fb4c5e95ef719b9442b0322e66b71461d29f2db58c074f95cd
          name: container-image
